"""initial migration with independent registered_users and friendships

Revision ID: 0ee4e9e7efae
Revises: 
Create Date: 2025-10-14 18:07:12.931681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ee4e9e7efae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registered_users',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pfp_path', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_index(op.f('ix_registered_users_email'), 'registered_users', ['email'], unique=True)
    op.create_index(op.f('ix_registered_users_id_user'), 'registered_users', ['id_user'], unique=False)
    op.create_index(op.f('ix_registered_users_nickname'), 'registered_users', ['nickname'], unique=True)
    op.create_table('friendships',
    sa.Column('id_friendship', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id_1', sa.Integer(), nullable=False),
    sa.Column('user_id_2', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id_1'], ['registered_users.id_user'], ),
    sa.ForeignKeyConstraint(['user_id_2'], ['registered_users.id_user'], ),
    sa.PrimaryKeyConstraint('id_friendship')
    )
    op.create_index(op.f('ix_friendships_id_friendship'), 'friendships', ['id_friendship'], unique=False)
    op.create_index(op.f('ix_friendships_user_id_1'), 'friendships', ['user_id_1'], unique=False)
    op.create_index(op.f('ix_friendships_user_id_2'), 'friendships', ['user_id_2'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_friendships_user_id_2'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_user_id_1'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_id_friendship'), table_name='friendships')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_registered_users_nickname'), table_name='registered_users')
    op.drop_index(op.f('ix_registered_users_id_user'), table_name='registered_users')
    op.drop_index(op.f('ix_registered_users_email'), table_name='registered_users')
    op.drop_table('registered_users')
    # ### end Alembic commands ###
