"""add_friend_chat_table

Revision ID: 329175d0115e
Revises: 71f22fb57122
Create Date: 2025-10-21 17:44:01.294218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '329175d0115e'
down_revision: Union[str, None] = '71f22fb57122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_chats',
    sa.Column('id_friend_chat', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('friendship_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friendship_id'], ['friendships.id_friendship'], ),
    sa.PrimaryKeyConstraint('id_friend_chat')
    )
    op.create_index(op.f('ix_friend_chats_friendship_id'), 'friend_chats', ['friendship_id'], unique=True)
    op.create_index(op.f('ix_friend_chats_id_friend_chat'), 'friend_chats', ['id_friend_chat'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_friend_chats_id_friend_chat'), table_name='friend_chats')
    op.drop_index(op.f('ix_friend_chats_friendship_id'), table_name='friend_chats')
    op.drop_table('friend_chats')
    # ### end Alembic commands ###
