"""add_chat_message_table

Revision ID: 563f3c5e5ac8
Revises: 329175d0115e
Create Date: 2025-10-21 17:55:21.035405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '563f3c5e5ac8'
down_revision: Union[str, None] = '329175d0115e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id_message', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('friend_chat_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['friend_chat_id'], ['friend_chats.id_friend_chat'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['registered_users.id'], ),
    sa.PrimaryKeyConstraint('id_message')
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_friend_chat_id'), 'chat_messages', ['friend_chat_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_id_message'), 'chat_messages', ['id_message'], unique=False)
    op.create_index(op.f('ix_chat_messages_sender_id'), 'chat_messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_sender_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_id_message'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_friend_chat_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
