"""Link user to registered_user

Revision ID: 875222a9782c
Revises: 9582d64e0589
Create Date: 2025-10-14 16:50:31.929171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '875222a9782c'
down_revision: Union[str, None] = '9582d64e0589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registered_users', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index('ix_registered_users_id', table_name='registered_users')
    op.create_index(op.f('ix_registered_users_user_id'), 'registered_users', ['user_id'], unique=False)
    op.create_foreign_key(None, 'registered_users', 'users', ['user_id'], ['id_user'])
    op.drop_column('registered_users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registered_users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'registered_users', type_='foreignkey')
    op.drop_index(op.f('ix_registered_users_user_id'), table_name='registered_users')
    op.create_index('ix_registered_users_id', 'registered_users', ['id'], unique=False)
    op.drop_column('registered_users', 'user_id')
    # ### end Alembic commands ###
