"""add_elo_to_registered_user

Revision ID: 93c6bf288d1c
Revises: 9d01d30271fb
Create Date: 2025-11-20 20:33:48.823165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93c6bf288d1c'
down_revision: Union[str, None] = '9d01d30271fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registered_users', sa.Column('elo', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registered_users', 'elo')
    # ### end Alembic commands ###
