"""Create registered_users table

Revision ID: 9582d64e0589
Revises: 6a1036a13c9f
Create Date: 2025-10-14 16:44:17.436141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9582d64e0589'
down_revision: Union[str, None] = '6a1036a13c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registered_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pfp_path', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registered_users_email'), 'registered_users', ['email'], unique=True)
    op.create_index(op.f('ix_registered_users_id'), 'registered_users', ['id'], unique=False)
    op.create_index(op.f('ix_registered_users_login'), 'registered_users', ['login'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registered_users_login'), table_name='registered_users')
    op.drop_index(op.f('ix_registered_users_id'), table_name='registered_users')
    op.drop_index(op.f('ix_registered_users_email'), table_name='registered_users')
    op.drop_table('registered_users')
    # ### end Alembic commands ###
