"""Create friendships table

Revision ID: e53e06ee675f
Revises: 875222a9782c
Create Date: 2025-10-14 16:55:48.576949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e53e06ee675f'
down_revision: Union[str, None] = '875222a9782c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('id_friendship', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id_1', sa.Integer(), nullable=False),
    sa.Column('user_id_2', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id_1'], ['registered_users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id_2'], ['registered_users.user_id'], ),
    sa.PrimaryKeyConstraint('id_friendship')
    )
    op.create_index(op.f('ix_friendships_id_friendship'), 'friendships', ['id_friendship'], unique=False)
    op.create_index(op.f('ix_friendships_user_id_1'), 'friendships', ['user_id_1'], unique=False)
    op.create_index(op.f('ix_friendships_user_id_2'), 'friendships', ['user_id_2'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_friendships_user_id_2'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_user_id_1'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_id_friendship'), table_name='friendships')
    op.drop_table('friendships')
    # ### end Alembic commands ###
